### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by phoe** [euslisp/ansi-test#52]

**Comment by Affonso-Gui** [comment]
This repository is forked from https://gitlab.common-lisp.net/ansi-test/ansi-test, which also does not specify a LICENSE.

In this case it doesn't seem appropriate to add a LICENSE just to this forked repository.
@k-okada  What do you think?

**Comment by phoe** [comment]
Upstream ticket: https://gitlab.common-lisp.net/ansi-test/ansi-test/-/issues/26

**Comment by Affonso-Gui** [comment]
Created a PR at https://github.com/euslisp/ansi-test/pull/53 to restore the licensing information at `rt-doc.txt`, which I had overlooked and accidentally deleted (oops).

If the discussion at upstream leads to the adding of a template MIT license we shall update the license text as well.

**Comment by k-okada** [comment]
thanks good to know that
