### ISSUE TITLE
Strange error I could not identify the root of

### ISSUE THREAD

**Issue by ericlesaquiles** [euslisp/ansi-test#8]
I'm currently running the number tests ( `roseus eus-test.l`), loading only the numbers folder and getting repeatedly the following error:
```

/opt/ros/kinetic/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: no catcher found in (reset)
/opt/ros/kinetic/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0 no catcher found ***UNBOUND******UNBOUND*** in (reset)
```

It doesn't appear only for the numbers's tests, by the way.. It might be a very simple error, but, much as I tried, couldn't see the reason for it.

The (I think, only) relevant change I made before getting the error was in the 14th line of eus-test.l, turning

`
(if msg2 (format *error-output* " ~A" msg2))
`

into

`(if (ignore-errors msg2) (format *error-output* " ~A" msg2))`

in order to avoid "undefined variable" errors for msg2. For what I've seen, (if I've seen correctly) reset makes a throw, which should probably require a catch. But I'm unsure about what to do about it (maybe put a catch somewhere? where?)
I've tried digging into the code files for hints on the reason for error and how to fix it,  but remain clueless as for now (except for the not-too-spirited remark above). I'm sorry about that, as this is probably a very simple error I just don't have the eyes to see completely.

Would appreciate some help

**Comment by Affonso-Gui** [comment]
This is actually one bug of this test package. I am not sure why it happens, but guessing it has something to do with the order error handlers are installed.

for now, comment out [these lines](https://github.com/euslisp/ansi-test/blob/gsoc2018/eus-test.l#L104-L112) from eus-test.l, run `roseus eus-test.l` and try `(load numbers/load.lsp)`.

This shows the error message clearly:
```
ERROR: unbound variable most-negative-short-float in (rational-safely most-negative-short-float)
```

**Comment by Affonso-Gui** [comment]
Installing error handler after loading files solves the problem. #10

**Comment by ericlesaquiles** [comment]
Oh yes, sorry about that.. I had forgotten to tell that that error was after I'd define `most-negative-short-float` on the `setq` at line 63, which would yield a different error message.

However, oddly enough, after updating the file with your upgrades, any error (for numbers, that is) disappears. Momentarily, that is, for, after running a few more times,  it catches an undefined function error with `integer-decode-float` (and it's fatal). By the way, that's something I almost forgot to mention.. Namely, that function, as a good handful of others defined for CL, has the multiple-value-return as an important property. Maybe we could implement it, after dealing with some of the other errors. What do you people think? I found a paper which shows an efficient implementation (with continuation passing style, I think it might not be a great problem).

**Comment by Affonso-Gui** [comment]
Let's discuss more about multiple value implementation on today's meeting.

**Comment by Affonso-Gui** [comment]
Can we close this?
