### ISSUE TITLE
On llib loop

### ISSUE THREAD

**Issue by ericlesaquiles** [euslisp/ansi-test#9]
I've seen there is a `loop.l` file in the `lib/llib` folder. Not that it is used (indeed, a simple "load" doesn't do it, due to package issues, it seems), but I got curious on why it is there.. Just out of curiosity,  could someone tell me?

**Comment by Affonso-Gui** [comment]
Apparently eus already had a version of loop (I did not know it too!).

It says `no such package`, so you can load it after you define the `loop` package:
```
(make-package "LOOP")
(load "lib/llib/loop.l")
```
And run it normally:
```
$ (loop for x to 3 do (print x))
0
1
2
3
nil
```

However, it was implemented in 1986, so is not quite up-to-date.
```
(loop for x upto 3 do (print x))
;; ERROR: Unknown keyword in FOR or AS clause in LOOP
```
